name: Upload charm

on:
  workflow_dispatch:
    inputs:
      artifact_id:
        type: number
        required: true

jobs:
  upload_charm:
    runs-on: ubuntu-latest
    steps:
      - name: load images into local docker registry
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/canonical/livepatch-server/actions/artifacts/${{ inputs.artifact_id }}/zip --output artifact.zip
          ls -la
          tar -xzvf artifact.zip
          docker load -i livepatch-server.tar
          docker load -i schema-tool.tar

      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@main
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GH_PAT }}"
          channel: "latest/edge"
          pull-image: "false"
          tag-prefix: "k8s"
