name: Upload charm

on:
  workflow_dispatch:
    inputs:
      run_id:
        type: number
        required: true

jobs:
  upload_charm:
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          repository: canonical/livepatch-server
          github-token: "${{ secrets.GH_PAT }}"
          run-id: ${{ inputs.run_id }}
          merge-multiple: true

      - name: load images into local docker registry
        run: |
          ls -la
          if [ -f artifact.zip ]; then
              tar -xzvf artifact.zip
          else
              echo "artifact.zip file is automatically extracted."
          fi
          docker load -i livepatch-server.tar
          docker load -i schema-tool.tar

      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@main
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GH_PAT }}"
          channel: "latest/edge"
          pull-image: "false"
          tag-prefix: "k8s"
